### ISSUE TITLE
Notice: Undefined variable: show_chostname

### ISSUE THREAD

**Issue by mshoaib67** [goautodial/ce-www#5]
Hi,
After updating the gouatodial to new version using git has led us to errors in Agent pages & admin panel

[Admin Panel]

Notice: Undefined variable: show_chostname in /var/www/html/application/views/phpsysinfo/includes/xml/vitals.php on line 39

Notice: Undefined variable: show_ip_addr in /var/www/html/application/views/phpsysinfo/includes/xml/vitals.php on line 40

Deprecated: Function split() is deprecated in /var/www/html/application/views/phpsysinfo/includes/os/class.Linux.inc.php on line 137

[Agent Login Page]

Warning: date() [function.date]: It is not safe to rely on the system's timezone settings. You are *required* to use the date.timezone setting or the date_default_timezone_set() function. In case you used any of those methods and you are still getting this warning, you most likely misspelled the timezone identifier. We selected 'Europe/Berlin' for 'CEST/2.0/DST' instead in /var/www/html/agent/agent.php on line 474

Warning: date() [function.date]: It is not safe to rely on the system's timezone settings. You are *required* to use the date.timezone setting or the date_default_timezone_set() function. In case you used any of those methods and you are still getting this warning, you most likely misspelled the timezone identifier. We selected 'Europe/Berlin' for 'CEST/2.0/DST' instead in /var/www/html/agent/agent.php on line 475

Warning: date() [function.date]: It is not safe to rely on the system's timezone settings. You are *required* to use the date.timezone setting or the date_default_timezone_set() function. In case you used any of those methods and you are still getting this warning, you most likely misspelled the timezone identifier. We selected 'Europe/Berlin' for 'CEST/2.0/DST' instead in /var/www/html/agent/agent.php on line 476

Warning: date() [function.date]: It is not safe to rely on the system's timezone settings. You are *required* to use the date.timezone setting or the date_default_timezone_set() function. In case you used any of those methods and you are still getting this warning, you most likely misspelled the timezone identifier. We selected 'Europe/Berlin' for 'CEST/2.0/DST' instead in /var/www/html/agent/agent.php on line 477

**Comment by mmixx** [comment]
Hi,

Have you checked on your server's /etc/php.ini file if display_errors is enabled or turned On?

Cheers,
Chris

**Comment by mshoaib67** [comment]
Hi,
Yes display_errors = off in the php.ini file.

i just sorted the issue. If we change memory limit in php.ini while installation or after that the error are displayed.
